spring.application.name=monsai

# Configurações do JWT
security.jwt.secret=monsaiSistemaSeguroJwtChaveMuitoForte123456
security.jwt.expiration=86400000

# ===============================
# CONFIGURAÇÕES DO BANCO MYSQL
# ===============================

# URL de conexão (O "createDatabaseIfNotExist=true" é um truque mágico para o Spring criar o banco sozinho!)
spring.datasource.url=jdbc:mysql://localhost:3306/monsai_db?createDatabaseIfNotExist=true&serverTimezone=UTC

# Seu usuário do MySQL (Geralmente é root quando instalamos localmente)
spring.datasource.username=root

# A senha que você configurou quando instalou o MySQL no seu PC
spring.datasource.password=senaisp

# ===============================
# CONFIGURAÇÕES DO HIBERNATE (JPA)
# ===============================

# UPDATE: Cria as tabelas se não existirem, e atualiza se você mudar algo nas Entidades. Nunca apaga os dados!
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está executando (Ótimo para debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Configuração do broker (exemplo local)
# Configurações do Broker Local (AACI-122)
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=monsai-backend-api
mqtt.username=
mqtt.password=

# Configurações adicionais
mqtt.clean-session=true
mqtt.automatic-reconnect=true
mqtt.keep-alive-interval=60
mqtt.connection-timeout=30
mqtt.default-qos=1

# Definição do tópico MQTT
mqtt.topic=monsai/telemetria

# Exemplo com SSL
# mqtt.broker-url=ssl://meu-broker:8883
# javax.net.ssl.trustStore=classpath:meu_truststore.jks
# javax.net.ssl.trustStorePassword=minhasenha
# javax.net.ssl.trustStoreType=JKS