spring.application.name=monsai
security.jwt.secret=monsaiSistemaSeguroJwtChaveMuitoForte123456
security.jwt.expiration=86400000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=monsai-backend-api
mqtt.username=
mqtt.password=
mqtt.clean-session=true
mqtt.automatic-reconnect=true
mqtt.keep-alive-interval=60
mqtt.connection-timeout=30
mqtt.default-qos=1
mqtt.topic=monsai/telemetria
