spring.application.name=monsai

# Configurações do JWT
security.jwt.secret=monsaiSistemaSeguroJwtChaveMuitoForte123456
security.jwt.expiration=86400000

# Configurações do Banco de Dados em Memória (H2)
spring.datasource.url=jdbc:h2:mem:monsaidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Pede pro Hibernate criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Libera o painel visual do banco no navegador (opcional, mas muito útil)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do broker (exemplo local)
# Configurações do Broker Local (AACI-122)
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=monsai-backend-api
mqtt.username=
mqtt.password=

# Configurações adicionais
mqtt.clean-session=true
mqtt.automatic-reconnect=true
mqtt.keep-alive-interval=60
mqtt.connection-timeout=30
mqtt.default-qos=1

# Teste no computador pessoal do André
#server.port=8081

# Exemplo com SSL
# mqtt.broker-url=ssl://meu-broker:8883
# javax.net.ssl.trustStore=classpath:meu_truststore.jks
# javax.net.ssl.trustStorePassword=minhasenha
# javax.net.ssl.trustStoreType=JKS